---
- name: Installer Docker et Docker Compose sur Debian
  hosts: all
  become: yes
  vars:
    user: benjamin

  tasks:
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installer les dépendances nécessaires
      apt:
        state: latest
        update_cache: yes
        name:
          - git
          - zsh
  
  roles:
    - role: user
    - role: docker
    
   
