---
- name: Installation des serveurs web
  hosts: web
  become: true

  tasks:
    - name: Mise à jour du vps
      raw: sudo apt update && sudo apt install -y
    - name: Install packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      with_items:
        - git
        - docker.io
        - docker compose

  # clones repo
